application:

  name: gestion-academica

  version: 1.0.0

server:

  host: localhost

  port: 5002 

security:

  mock_enabled: true

  auth_enabled: false

  jwt_enabled: false

auth:

  url: http://localhost:5003

redis:

  host: localhost

  port: 6379