microservicio:

  id: 02
  nombre: micro2

acciones:

  # ----------------------------------
  # INSCRIPCIONES
  # ----------------------------------

  - micro2.inscripciones.crear
  - micro2.inscripciones.leer
  - micro2.inscripciones.actualizar
  - micro2.inscripciones.eliminar

  # ----------------------------------
  # CLASES
  # ----------------------------------

  - micro2.clases.crear
  - micro2.clases.leer
  - micro2.clases.actualizar
  - micro2.clases.eliminar

  # ----------------------------------
  # ASISTENCIAS
  # ----------------------------------

  - micro2.asistencias.crear
  - micro2.asistencias.leer
  - micro2.asistencias.actualizar
  - micro2.asistencias.eliminar

  # ----------------------------------
  # EVALUACIONES
  # ----------------------------------

  - micro2.evaluaciones.crear
  - micro2.evaluaciones.leer
  - micro2.evaluaciones.actualizar
  - micro2.evaluaciones.eliminar

  # ----------------------------------
  # CALIFICACIONES
  # ----------------------------------

  - micro2.calificaciones.crear
  - micro2.calificaciones.leer
  - micro2.calificaciones.actualizar
  - micro2.calificaciones.eliminar

  # ----------------------------------
  # RESULTADO ACADÉMICO
  # ----------------------------------

  - micro2.resultado_academico.generar
  - micro2.resultado_academico.leer
  - micro2.resultado_academico.eliminar

  # ----------------------------------
  # RESULTADO PLAN
  # ----------------------------------

  - micro2.resultado_plan.leer
  - micro2.resultado_plan.actualizar
  - micro2.resultado_plan.eliminar

  # ----------------------------------
  # CERTIFICADOS
  # ----------------------------------

  - micro2.certificados.emitir
  - micro2.certificados.leer
  - micro2.certificados.actualizar
  - micro2.certificados.eliminar

  # ----------------------------------
  # REPORTES
  # ----------------------------------

  - micro2.reportes.leer