usuarios:

  - id: 1
    usuario: admin
    nombre: Juan Pérez
    cargo: Administrador del Microservicio
    email: juan.perez@instituto.edu.ar
    activo: true
    roles:
      - id: 1
        nombre: Administrador Microservicio

  - id: 2
    usuario: docente
    nombre: Laura Martínez
    cargo: Docente
    email: laura.martinez@instituto.edu.ar
    activo: true
    roles:
      - id: 10
        nombre: Docencia

  - id: 3
    usuario: alumno
    nombre: Agustina Herrera
    cargo: Alumna
    email: agustina.herrera@instituto.edu.ar
    activo: true
    roles:
      - id: 8
        nombre: Alumno

