from .inscripcion_routes import inscripcion_bp
from .clase_routes import clase_bp
from .asistencia_routes import asistencia_bp
from .evaluacion_routes import evaluacion_bp
from .calificacion_routes import calificacion_bp
from .resultado_academico_routes import resultado_academico_bp
from .resultado_plan_routes import resultado_plan_bp
from .certificado_routes import certificado_bp
from .auth_routes_mock import auth_bp