version: "3.9"

services:

  backend:

    build:
      context: ../backend
      dockerfile: Dockerfile

    container_name: gestion-academica-backend

    restart: always

    ports:
      - "5000:5000"

    environment:
      - PORT=5000

    volumes:
      - ../backend:/app

    networks:
      red_bomberos_estatica:
        ipv4_address: 172.10.10.21

  frontend:

    build:
      context: ../frontend
      dockerfile: Dockerfile

    container_name: gestion-academica-frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "5173:5173"

    volumes:
      - ../frontend:/app
      - /app/node_modules

    networks:
      red_bomberos_estatica:
        ipv4_address: 172.10.10.31

networks:

  red_bomberos_estatica:
    driver: bridge

    ipam:
      config:
        - subnet: 172.10.10.0/24