version: "3.9"

services:

  postgres:
    image: postgres:17

    container_name: gestion-academica-db

    restart: always

    environment:
      POSTGRES_DB: gestion_academica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      red_bomberos_estatica:
        ipv4_address: 172.10.10.11

  backend:

    build:
      context: ../backend
      dockerfile: Dockerfile

    container_name: gestion-academica-backend

    restart: always

    depends_on:
      - postgres
    
    command: sh -c "pip install -e /auth-common --quiet && python app.py"

    ports:
      - "5000:5000"
    
    env_file:
      - ../backend/.env

    environment:
      PORT: 5000

    volumes:
      - ../backend:/app
      - ../../auth-common:/auth-common

    networks:
      red_bomberos_estatica:
        ipv4_address: 172.10.10.21

  frontend:

    build:
      context: ../frontend
      dockerfile: Dockerfile

    container_name: gestion-academica-frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "5173:5173"

    volumes:
      - ../frontend:/app
      - /app/node_modules

    networks:
      red_bomberos_estatica:
        ipv4_address: 172.10.10.31

networks:

  red_bomberos_estatica:
    driver: bridge

    ipam:
      config:
        - subnet: 172.10.10.0/24

volumes:
  postgres_data: